//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteIntoFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasteIntoFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next1 {
            get {
                object obj = ResourceManager.GetObject("next1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave.
        /// </summary>
        internal static string str_autosave {
            get {
                return ResourceManager.GetString("str_autosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard content has been automatically saved as {0}.
        /// </summary>
        internal static string str_autosave_balloontext {
            get {
                return ResourceManager.GetString("str_autosave_balloontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard saved to file.
        /// </summary>
        internal static string str_autosave_balloontitle {
            get {
                return ResourceManager.GetString("str_autosave_balloontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasteIntoFile will automatically save files without showing a dialog anymore. If you want to show the main window again, you will have to delete this file: {0}.
        /// </summary>
        internal static string str_autosave_infotext {
            get {
                return ResourceManager.GetString("str_autosave_infotext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear clipboard.
        /// </summary>
        internal static string str_clear_clipboard {
            get {
                return ResourceManager.GetString("str_clear_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Into File.
        /// </summary>
        internal static string str_contextentry {
            get {
                return ResourceManager.GetString("str_contextentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register context menu entry.
        /// </summary>
        internal static string str_contextentry_register {
            get {
                return ResourceManager.GetString("str_contextentry_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister context menu entry.
        /// </summary>
        internal static string str_contextentry_unregister {
            get {
                return ResourceManager.GetString("str_contextentry_unregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string str_ellipsis {
            get {
                return ResourceManager.GetString("str_ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string str_extension {
            get {
                return ResourceManager.GetString("str_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string str_filename {
            get {
                return ResourceManager.GetString("str_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originally created by Eslam Hamouda.
        /// </summary>
        internal static string str_firstlaunch_creator {
            get {
                return ResourceManager.GetString("str_firstlaunch_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EslaMx7/PasteIntoFile.
        /// </summary>
        internal static string str_firstlaunch_creator_link {
            get {
                return ResourceManager.GetString("str_firstlaunch_creator_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved and maintained by Francesco Sorge.
        /// </summary>
        internal static string str_firstlaunch_maintainer {
            get {
                return ResourceManager.GetString("str_firstlaunch_maintainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gitlab.com/fsorge/PasteIntoFile.
        /// </summary>
        internal static string str_firstlaunch_maintainer_link {
            get {
                return ResourceManager.GetString("str_firstlaunch_maintainer_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add context menu entry?.
        /// </summary>
        internal static string str_firstlaunch_register {
            get {
                return ResourceManager.GetString("str_firstlaunch_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By adding an entry to the File Explorer context menu, you can quickly paste clipboard contents into a file by right-clicking on your desktop or in any folder, and choosing &apos;{0}&apos;..
        /// </summary>
        internal static string str_firstlaunch_register_explain {
            get {
                return ResourceManager.GetString("str_firstlaunch_register_explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to
        ///Paste Into File.
        /// </summary>
        internal static string str_firstlaunch_welcome {
            get {
                return ResourceManager.GetString("str_firstlaunch_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Into File – First Launch.
        /// </summary>
        internal static string str_firstlaunch_windowtitle {
            get {
                return ResourceManager.GetString("str_firstlaunch_windowtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string str_location {
            get {
                return ResourceManager.GetString("str_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forked and improved by Francesco Sorge.
        /// </summary>
        internal static string str_main_info {
            get {
                return ResourceManager.GetString("str_main_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.francescosorge.com.
        /// </summary>
        internal static string str_main_info_url {
            get {
                return ResourceManager.GetString("str_main_info_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Into File.
        /// </summary>
        internal static string str_main_window_title {
            get {
                return ResourceManager.GetString("str_main_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you are running this application for the first time,
        ///do you want to add an entry to the explorer context menu?.
        /// </summary>
        internal static string str_message_first_time {
            get {
                return ResourceManager.GetString("str_message_first_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Into File helps you paste any text or images in your system clipboard into a file directly instead of creating new file yourself
        ///      
        ///--------------------
        ///      
        ///To Register the application to your system context menu run the program as administrator with this argument : /reg
        ///to Unregister the application use this argument : /unreg
        ///To change the format of the default filename, use this argument: /filename &quot;yyyy-MM-dd HH-mm-ss&quot;
        ///
        ///--------------------
        ///
        ///https://gitlab.com/fsorge/PasteIntoFile        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string str_message_help {
            get {
                return ResourceManager.GetString("str_message_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer context menu entry has been added.
        /// </summary>
        internal static string str_message_register_context_menu_success {
            get {
                return ResourceManager.GetString("str_message_register_context_menu_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename-template has been registered.
        /// </summary>
        internal static string str_message_register_filename_success {
            get {
                return ResourceManager.GetString("str_message_register_filename_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the application as Administrator!.
        /// </summary>
        internal static string str_message_run_as_admin {
            get {
                return ResourceManager.GetString("str_message_run_as_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer context menu entry has been removed.
        /// </summary>
        internal static string str_message_unregister_context_menu_success {
            get {
                return ResourceManager.GetString("str_message_unregister_context_menu_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks.
        /// </summary>
        internal static string str_no {
            get {
                return ResourceManager.GetString("str_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty.
        /// </summary>
        internal static string str_noclip_text {
            get {
                return ResourceManager.GetString("str_noclip_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string str_save {
            get {
                return ResourceManager.GetString("str_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder for saving this file .
        /// </summary>
        internal static string str_select_folder {
            get {
                return ResourceManager.GetString("str_select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file.
        /// </summary>
        internal static string str_type_img {
            get {
                return ResourceManager.GetString("str_type_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        internal static string str_type_txt {
            get {
                return ResourceManager.GetString("str_type_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file.
        /// </summary>
        internal static string str_type_unknown {
            get {
                return ResourceManager.GetString("str_type_unknown", resourceCulture);
            }
        }
    }
}
