project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true
files:
  - source: Resources.resx
    translation: /%original_path%/Resources.%two_letters_code%.resx
    skip_untranslated_strings: true
