name: Sync translations with Crowdin

on:
  push:
    branches: [ maincr ]
    paths:
      - '**/Resources*.resx'
  workflow_dispatch:

env:
  # The git branch used for sync with crowdin to keep track of changes from crowdin.
  # Also used for the pull request. Must not be deleted even after the PR is merged!
  BRANCH: $GITHUB_REF-crowdin
  # Source and translation file paths to sync
  SOURCE: '**/Resources.resx'
  TRANSLATION: '/%original_path%/Resources.%two_letters_code%.resx'

concurrency:
  group: ${{ github.workflow }}

jobs:
  sync:
    name: Sync translations with crowdin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Prepare
      run: |
        git config user.name "Crowdin Bot"
        git config user.email "<>"
        git checkout $GITHUB_REF
        git checkout $BRANCH 2>/dev/null || git checkout -b $BRANCH
        git checkout -B crowdin_tmp $BRANCH

    - name: Pull changes from crowdin
      uses: crowdin/github-action@1.5.2
      with:
        upload_sources: false
        upload_translations: false
        download_translations: true

        localization_branch_name: crowdin_tmp
        create_pull_request: false
        push_translations: false        
        source: $SOURCE
        translation: $TRANSLATION
        preserve_hierarchy: true
        
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        crowdin_branch_name: main

    - name: Merge and resolve conflicts
      run: |
        git status
        git log
        git add .
        git commit -m "Update from crowdin"
        git status
        git log        
        git merge $GITHUB_REF -Xtheirs -v

    - name: Push to crowdin
      uses: crowdin/github-action@1.5.2
      with:
        upload_sources: true
        upload_translations: true
        download_translations: false
        
        source: $SOURCE
        translation: $TRANSLATION
        preserve_hierarchy: true
        
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        crowdin_branch_name: main


  pull_request:
    name: Create pull request
    needs: sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clean branch
      run: |
        git checkout -B $BRANCH $GITHUB_REF

    - name: Pull request
      uses: crowdin/github-action@1.5.2
      with:
        upload_sources: false
        upload_translations: false
        download_translations: true

        localization_branch_name: $BRANCH
        pull_request_base_branch_name: $GITHUB_REF
        skip_untranslated_strings: true
        export_only_approved: false
        commit_message: 'Crowdin translations'
        
        source: $SOURCE
        translation: $TRANSLATION
        preserve_hierarchy: true
        
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        crowdin_branch_name: main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}



