name: Auto-fix file format

# Since pre-commit.ci cannot run local hooks, run them here manually to fixup formatting in pull requests

on: pull_request

env:
  # SSH Deploy Key with write access (needed to trigger push workflow runs in created pull request)
  SSH_KEY: ${{ secrets.SSH_KEY_GITHUB_ACTION }}

jobs:
  pre-commit:
    name: Format files with pre-commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          ssh-key: ${{ env.SSH_KEY }}
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v3

      - name: Install pre-commit
        run: |
            python3 -m pip install pre-commit
            pre-commit install

      - name: Format files
        continue-on-error: true
        id: check
        run: |
          FILES=$(git diff --name-only HEAD origin/$GITHUB_BASE_REF | tr '\n' ' ')
          echo $FILES
          pre-commit run --files $FILES

      - name: Push formatted fixes
        if: steps.check.outcome == 'failure'
        run: |
          git config user.name "Bot"
          git config user.email "<action@github.com>"
          git commit -am "Fix file format [skip ci]"
          git push origin HEAD:${{github.event.pull_request.head.ref}}
