<?xml version="1.0" encoding="UTF-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyTitle>PasteIntoFile</AssemblyTitle>
        <AssemblyName>PasteIntoFile</AssemblyName>
        <Description>Paste Clipboard Contents Into Files</Description>
        <Company>github.com/eltos</Company>
        <Product>PasteIntoFile</Product>
        <Copyright>Copyright © PasteIntoFile GitHub contributors</Copyright>
        <AssemblyVersion>6.0.0.0</AssemblyVersion>
        <FileVersion>6.0.0.0</FileVersion>
        <Version>6.0.0</Version>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <RootNamespace>PasteIntoFile</RootNamespace>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <UseWindowsForms>true</UseWindowsForms>
        <ApplicationIcon>Resources/icon.ico</ApplicationIcon>
    </PropertyGroup>
    <!-- Build variants -->
    <PropertyGroup>
        <!-- Configuration: Debug, Release -->
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <!-- Configuration: AnyCPU -->
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
        <!-- Configuration: Installer, Portable -->
        <Flavor Condition=" '$(Flavor)' == '' ">Installer</Flavor>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>bin\Debug\</OutputPath>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\Release\</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Flavor)'=='Portable'">
        <DefineConstants>$(DefineConstants);PORTABLE</DefineConstants>
    </PropertyGroup>
    <!-- Project components -->
    <ItemGroup>
        <PackageReference Include="Csv" Version="2.0.245" />
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
        <PackageReference Include="CommandLineParser" Version="2.9.1" />
        <PackageReference Include="Ical.Net" Version="5.2.3" />
    </ItemGroup>
    <ItemGroup Condition="'$(Flavor)'=='Portable'">
        <PackageReference Include="PortableSettingsProvider" Version="0.2.4" />
    </ItemGroup>
    <ItemGroup>
        <None Include="app.manifest">
            <SubType>Designer</SubType>
        </None>
        <None Include="Properties\Settings.settings">
            <Generator>SettingsSingleFileGenerator</Generator>
            <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
        <None Include="App.config">
            <SubType>Designer</SubType>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Content Include="Resources\icon.ico" />
        <Content Include="Resources\icon.png" />
    </ItemGroup>
    <ItemGroup>
        <COMReference Include="SHDocVw">
            <Guid>{EAB22AC0-30C1-11CF-A7EB-0000C05BAE0B}</Guid>
            <VersionMajor>1</VersionMajor>
            <VersionMinor>1</VersionMinor>
            <Lcid>0</Lcid>
            <WrapperTool>tlbimp</WrapperTool>
            <Isolated>False</Isolated>
            <EmbedInteropTypes>True</EmbedInteropTypes>
        </COMReference>
        <COMReference Include="Shell32">
            <Guid>{50A7E9B0-70EF-11D1-B75A-00A0C90564FE}</Guid>
            <VersionMajor>1</VersionMajor>
            <VersionMinor>0</VersionMinor>
            <Lcid>0</Lcid>
            <WrapperTool>tlbimp</WrapperTool>
            <Isolated>False</Isolated>
            <EmbedInteropTypes>True</EmbedInteropTypes>
        </COMReference>
    </ItemGroup>
    <Target Name="CopyShellExtension" AfterTargets="Build">
        <ItemGroup>
            <ShellFiles Include="..\PasteIntoFileShellExtension\bin\$(Configuration)\**\*.*" />
        </ItemGroup>
        <Copy SourceFiles="@(ShellFiles)" DestinationFolder="$(OutDir)" />
    </Target>
    <!-- To modify your build process, add your task inside one of the targets below and uncomment it.
         Other similar extension points exist, see Microsoft.Common.targets.
    <Target Name="BeforeBuild">
    </Target>
    <Target Name="AfterBuild">
    </Target>
    -->
</Project>
